// Objective-C API for talking to gomobile Go package.
//   gobind -lang=objc gomobile
//
// File is generated by gobind. Do not edit.

#ifndef __Gomobile_H__
#define __Gomobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GomobileCredentialBlob;
@class GomobileEncodedPCRs;

@interface GomobileCredentialBlob : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable secret;
@property (nonatomic) NSData* _Nullable cred;
@property (nonatomic) NSData* _Nullable credSecret;
@end

/**
 * 	PCRs are returned encoded to CBOR because
	gobind can't return complex types such as
	arrays.
 */
@interface GomobileEncodedPCRs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable data;
@end

/**
 * 	CheckQuotesSignature verifies that all quotes coming from
	the attestation data in @encodedpp are signed by the
	attestation key @encodedak, and contains the anti replay
	nonce.

	It also asserts that the final PCRs values from the attestation
	data matches the quotes ones.
 */
FOUNDATION_EXPORT BOOL GomobileCheckQuotesSignature(NSData* _Nullable encodedak, NSData* _Nullable encodedpp, NSData* _Nullable nonce, NSError* _Nullable* _Nullable error);

/**
 * 	GetPCRs extracts, encodes and returns PCRs from the
	attestation data @encodedpp.
 */
FOUNDATION_EXPORT GomobileEncodedPCRs* _Nullable GomobileGetPCRs(NSData* _Nullable encodedpp, NSError* _Nullable* _Nullable error);

/**
 * 	MakeCredential generates a challenge used to assert that
	the attestation key @encodedap has been generated on the
	same TPM that the endorsement key @ekn + @eke.
 */
FOUNDATION_EXPORT GomobileCredentialBlob* _Nullable GomobileMakeCredential(NSData* _Nullable ekn, long eke, NSData* _Nullable encodedap, NSError* _Nullable* _Nullable error);

/**
 * 	ReplayEventLog verifies that the eventlog from @encodedpp
	matches the final PCRs values (that were previously checked
	against the quotes ones).
 */
FOUNDATION_EXPORT BOOL GomobileReplayEventLog(NSData* _Nullable encodedpp, NSError* _Nullable* _Nullable error);

#endif
