
// Objective-C API for talking to the following Go packages
//
//	gomobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gomobile_FRAMEWORK_H__
#define __Gomobile_FRAMEWORK_H__

#include "Gomobile.objc.h"
#include "Universe.objc.h"

#endif
